### ISSUE TITLE
Electrum dashboard exceeds the connection limit

### ISSUE THREAD

**Issue by Radiokot** [mu373/bitcoind-dashboard#14]
Hi, Minakun 😊  I have my node back again and continue setting up a dashboard for it. 
Currently, it seems that if the dashboard is visited multiple times throughout the day, it exceeds the Electrum server connection limit and stops showing the data until restarted.

Dashboard:
```
bitcoind_dashboard  | Electrum attempting reconnect...
bitcoind_dashboard  | Electrum attempting reconnect...
bitcoind_dashboard  | Electrum attempting reconnect...
```

Meanwhile, Fulcrum (Electrum server):
```
fulcrum  | [2024-10-16 05:41:31.199] <TcpSrv 0.0.0.0:50001> Connection limit (12) exceeded for 172.26.0.4, connection refused
fulcrum  | [2024-10-16 05:41:37.375] <TcpSrv 0.0.0.0:50001> Connection limit (12) exceeded for 172.26.0.4, connection refused
fulcrum  | [2024-10-16 05:41:42.508] <TcpSrv 0.0.0.0:50001> Connection limit (12) exceeded for 172.26.0.4, connection refused
```

**Comment by mu373** [comment]
Didn't realize that the connection wasn't closed properly, so thank you very much for the issue and PR.
I've confirmed that the dashboard is working properly after the merge!
