### ISSUE TITLE
Image doesn't build

### ISSUE THREAD

**Issue by Radiokot** [mu373/bitcoind-dashboard#2]
Hi. I'm trying to launch your dashboard but can't build the image for it. I get the following error:
```
 => [bitcoind_dashboard builder 4/4] RUN yarn build                                                                                                             49.5s
 => ERROR [bitcoind_dashboard runner 4/7] COPY --from=builder /app/public ./public                                                                               0.0s
------
 > [bitcoind_dashboard runner 4/7] COPY --from=builder /app/public ./public:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 2fb7937f-06d1-43ce-a37c-f0800131252b::c3fa1v8ve7czyc1a3ug4ey97f: "/app/public": not found
```

**Comment by mu373** [comment]
Hi, thanks for your comment. Making a blank `public` folder (`mkdir public`) in the repository root may solve the issue.

**Comment by mu373** [comment]
I was also able to reproduce this issue on my environment too.

> Making a blank public folder (mkdir public) in the repository root may solve the issue.

This worked. Or maybe I could delete the `COPY --from=builder /app/public ./public` line from the Dockerfile.

**Comment by Radiokot** [comment]
Thank you, Minakun, creation of an empty folder worked. I also had to remove all the quotes and inline comments from the env file, otherwise they get into the URL and credentials. 
The dashboard is now running, although I can't test it as my Electrum server is not yet synchronized, therefore doesn't respond to queries.

**Comment by mu373** [comment]
Glad that it worked! The template for`.env.local` was left outdated without reflecting the local changes, so I'll make sure to have it updated.

I also recognize that there should be an option to enable/disable Electrum section, and that is what I hope to implement in future (https://github.com/mu373/bitcoind-dashboard/issues/3).

**Comment by mu373** [comment]
@Radiokot Just released a new version after some updates. Please try it out if you're interested.
- Electrum panel can now be manually disabled/enabled by `ENABLE_ELECTRUM_PANEL=TRUE` in config.
- Data is now asynchronously loaded in the client side from the server API. Page loads much faster than before!

https://github.com/mu373/bitcoind-dashboard/releases/tag/v1.1.0

**Comment by Radiokot** [comment]
That's great news! Well done. 
Unfortunately, at the moment I no longer have an ability to experiment with Bitcoin node. But I will test your dashboard as soon I have it back.
